#!/bin/bash

START=$1
END=$2

# Get next 4 train info from specified line

if [ "$1" = "30th" ]; then
	# Ft. Wash. to 30th street
	TRAINS=$(wget -o wget.log -O- "http://app.septa.org/nta/result.php?loc_a=Ft+Washington&loc_z=30th+Street+Station" | grep '<td>')
elif [ "$1" = "fort" ]; then
	# 30th street to Ft. Wash.
	TRAINS=$(wget -o wget.log -O- "http://app.septa.org/nta/result.php?loc_a=30th+Street+Station&loc_z=Ft+Washington" | grep '<td>')
else
	TRAINS="!No valid trip was given!"
fi

echo $TRAINS


# Alternative method using sed to trim output instead of parsing with 'parse' script
wget -o ft230.log -O- "http://app.septa.org/nta/result.php?loc_a=Ft+Washington&loc_z=30th+Street+Station" | 
	grep "<td>" | 
	cut -d '>' -f 4,6,8,10,14,19,21,23,25,29,34,36,38,40,44,49,51,53,55,59 |
	sed -e 's/<\/td>/ /g' | sed -e 's/<\/td/ /g'
